### ISSUE TITLE
Episode vs Epsiode

### ISSUE THREAD

**Issue by pachadotdev** [tbradley1013/dundermifflin#3]
Hi! I saw the headers have a typo
Great package btw!!

**Comment by tbradley1013** [comment]
Hi @pachamaltese 

Can you elaborate on where this typo is? The data set and the `filter_quotes` functions all look to have the correct spelling to me.

**Comment by pachadotdev** [comment]
@tbradley1013 here's are the typos
https://github.com/tbradley1013/dundermifflin/blob/master/R/get-quotes.R#L44
https://github.com/tbradley1013/dundermifflin/blob/master/R/get-quotes.R#L60
great package!! I discovered those diving into the code

**Comment by tbradley1013** [comment]
Great, thanks for the catch! I have corrected the spelling. I am glad you enjoy the package!
